databases:
  - name: api_db
    plan: free
    databaseName: api_db
    user: api_db

services:
  - type: web
    name: api
    plan: free
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn api_project.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: api_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 2
      - key: DJANGO_SUPERUSER_PASSWORD
        generateValue: true