# Generated by Django 3.1 on 2022-07-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20220729_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content_en',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_ja',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_en',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_ja',
            field=models.CharField(max_length=100),
        ),
    ]
