# Generated by Django 3.1 on 2022-08-03 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20220729_2313'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
