# Generated by Django 3.1 on 2022-08-03 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_docs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='docs',
            options={'verbose_name_plural': 'Docs'},
        ),
    ]
