# Generated by Django 3.1 on 2022-08-20 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20220803_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='docs',
            name='description_en',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docs',
            name='description_ja',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='docs',
            name='content_en',
            field=models.TextField(blank=True, null=True),
        ),
    ]
