# Generated by Django 3.1 on 2022-08-20 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20220820_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docs',
            name='content_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='docs',
            name='description_ja',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='docs',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
