# Generated by Django 3.1 on 2022-08-20 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20220820_1732'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Talk',
        ),
    ]
