# Generated by Django 3.1 on 2022-08-20 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20220820_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='description_en',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='talk',
            name='description_ja',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
