# Generated by Django 3.1 on 2022-08-20 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20220820_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='description_en',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='talk',
            name='description_ja',
            field=models.TextField(default=''),
        ),
    ]
