# Generated by Django 3.1 on 2022-08-20 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_auto_20220820_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='content_en',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='talk',
            name='content_ja',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='talk',
            name='description_en',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='talk',
            name='description_ja',
            field=models.TextField(),
        ),
    ]
