# Generated by Django 3.1 on 2022-08-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_build'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='description_en',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='build',
            name='description_ja',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='build',
            name='slug',
            field=models.SlugField(default='', max_length=300),
        ),
    ]
