# Generated by Django 3.1 on 2022-08-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_auto_20220820_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='slug',
            field=models.SlugField(max_length=300),
        ),
    ]
