# Generated by Django 3.1 on 2022-08-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_auto_20220820_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
        migrations.AlterField(
            model_name='talk',
            name='description_en',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='talk',
            name='description_ja',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='talk',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
    ]
