# Generated by Django 3.1 on 2022-08-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_auto_20220820_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docs',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
    ]
