# Generated by Django 3.1 on 2022-08-20 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_auto_20220820_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docs',
            name='content_en',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='docs',
            name='description_en',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='docs',
            name='description_ja',
            field=models.TextField(default='', max_length=300),
        ),
    ]
