# Generated by Django 3.1 on 2022-08-20 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_auto_20220820_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docs',
            name='title_ja',
            field=models.CharField(default='', max_length=100),
        ),
    ]
