# Generated by Django 3.1 on 2022-08-20 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_auto_20220820_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docs',
            name='title_ja',
            field=models.CharField(max_length=100),
        ),
    ]
