# Generated by Django 3.1 on 2022-08-26 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_auto_20220820_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docs',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
