# Generated by Django 3.1 on 2022-08-26 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_auto_20220826_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docs',
            name='id',
            field=models.AutoField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
